name: ArgoCD Application Health Check
description: A GitHub Action that monitors and reports the health status of ArgoCD applications, providing detailed diagnostics for unhealthy resources including events, pod logs, and intelligent log parsing.

author: CDQ AG
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  app-name:
    description: 'Name of the application'
    required: true

  server-url:
    description: 'ArgoCD server URL'
    required: true

  user-login:
    description: 'User login'
    required: true

  user-password:
    description: 'User password'
    required: true

  fail-on-unhealthy:
    description: 'Fail the action if the application is unhealthy'
    default: 'false'

outputs:
  app-health:
    description: 'Health status of the application'

runs:
  using: node20
  main: dist/main.js
