name: ArgoCD Application Health Check
description: This GitHub Action prints given log file line by line, tries to parse it, and adds proper annotations to the lines.

author: CDQ AG
branding:
  icon: 'activity'
  color: 'orange'

inputs:
  app-name:
    description: 'Name of the application'
    required: true

  server-url:
    description: 'ArgoCD server URL'
    required: true

  user-login:
    description: 'User login'
    required: true

  user-password:
    description: 'User password'
    required: true

runs:
  using: node20
  main: dist/main.js
